apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-config
  namespace: default
  labels:
    app: mcp-backend
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: mcp
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/version: "1.0"
data:
  LOG_LEVEL: "INFO"
  MCP_ENV: "production"
# NOTE: Do not put secrets here. Use Secret for sensitive values. 