apiVersion: v1
kind: Secret
metadata:
  name: mcp-secrets
  namespace: default
  labels:
    app: mcp-backend
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: mcp
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/version: "1.0"
type: Opaque
data:
  DATABASE_URL: <base64-encoded-postgres-url>
  REDIS_URL: <base64-encoded-redis-url>
  MCP_API_KEY: <base64-encoded-api-key>
  POSTGRES_DB: <base64-encoded-db-name>
  POSTGRES_USER: <base64-encoded-db-user>
  POSTGRES_PASSWORD: <base64-encoded-db-password>
# NOTE: All values must be base64-encoded. Use `echo -n 'value' | base64` to encode. 